### ISSUE TITLE
현재 ApiResponse 클래스에서 성공했을 때와 실패했을 때 동작이 똑같습니다.

### ISSUE THREAD

**Issue by dlfdyd96** [prgrms-be-devcourse/BEDV1_Ddaangn#11]
어떻게 개선을 해야할까요?

**Comment by sds1vrk** [comment]
https://devlog-wjdrbs96.tistory.com/182
스프링에서 제공해주는 이 방법으로 추가하는건 어떻게 생각하세요?!

**Comment by dlfdyd96** [comment]
오 좋을 것 같아요! 다음엔 ResponseEntity를 사용한다면 응답에 대한 보일러플레이트를 적절히 적용할 수 있겠어용 : ) 지금은... 너무 범벅이라서 ㅎㅎ ;; 다음 프로젝트나 다음 스프린트가 있다면 적용해보도록 해용 : )
